### ISSUE TITLE
Unable to login. Prisma Error after initial login. Digest: 4031165855

### ISSUE THREAD

**Issue by chklff** [AntonioErdeljac/next13-trello#12]
After org creation I press the SKIP on invite collegues popup and  Vercel returns white screen with:

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 4031165855

Versel Log:

`PrismaClientKnownRequestError: 
Invalid `prisma.orgSubscription.findUnique()` invocation:

The table `OrgSubscription` does not exist in the current database.
    at Cn.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6817)
    at Cn.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:123:6206)
    at Cn.request (/var/task/node_modules/@prisma/client/runtime/library.js:123:5926)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:128:9968)
    at async checkSubscription (/var/task/.next/server/chunks/365.js:1:2414)
    at async OrganizationIdPage (/var/task/.next/server/app/(platform)/(dashboard)/organization/[organizationId]/page.js:3:729) {
  code: 'P2021',
  clientVersion: '5.5.2',
  meta: { table: 'OrgSubscription' }
}

`
![CleanShot 2024-04-03 at 23 18 57@2x](https://github.com/AntonioErdeljac/next13-trello/assets/12959865/6e84224d-b776-4014-b382-e5de1f8c47b0)

@AntonioErdeljac  please take a look. Maybe it's my MySQL running in docker but all Db Clients work fine with it

Thanks a lot!

**Comment by chklff** [comment]
my bad,        
Here would be correct config
`mysql://root:my-secret-pw@1.1.1.1:3306/mydb?sslaccept=accept_invalid_certs` 

According to the https://www.prisma.io/docs/orm/overview/databases/mysql if you don't have proper SSL/domain and just use test server and Docker use:
**_sslaccept=accept_invalid_certs_**
